//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.InfoExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ask
    {
        public Ask()
        {
            this.AskLegs = new HashSet<AskLeg>();
            this.OrderLegs = new HashSet<OrderLeg>();
            this.Orders = new HashSet<Order>();
        }
    
        public long AskID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> CommoditySellID { get; set; }
        public Nullable<int> CommodityBuyID { get; set; }
        public Nullable<long> SellRatio { get; set; }
        public Nullable<long> BuyRatio { get; set; }
        public Nullable<long> BuyQuantity { get; set; }
        public Nullable<long> SellQuantity { get; set; }
        public bool AllowPartialFill { get; set; }
        public bool ApplyCommissionToBuy { get; set; }
        public System.DateTime AskDate { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
        public Nullable<long> MinBuyQuantity { get; set; }
        public Nullable<long> MinSellQuantity { get; set; }
        public Nullable<long> StartBuyQuantity { get; set; }
        public Nullable<long> StartSellQuantity { get; set; }
        public int MaxLegDepth { get; set; }
    
        public virtual ICollection<AskLeg> AskLegs { get; set; }
        public virtual Commodity CommodityBuy { get; set; }
        public virtual Commodity CommoditySell { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderLeg> OrderLegs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
