//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.InfoExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public Commodity()
        {
            this.CommissionOrders = new HashSet<Order>();
            this.BuyOrders = new HashSet<Order>();
            this.SellOrders = new HashSet<Order>();
            this.SellOrderLegs = new HashSet<OrderLeg>();
            this.BuyOrderLegs = new HashSet<OrderLeg>();
            this.CommissionOrderLegs = new HashSet<OrderLeg>();
            this.AskLegs = new HashSet<AskLeg>();
            this.AskLegs1 = new HashSet<AskLeg>();
            this.Asks = new HashSet<Ask>();
            this.Asks1 = new HashSet<Ask>();
        }
    
        public int CommodityID { get; set; }
        public string CommodityName { get; set; }
        public string Symbol { get; set; }
    
        public virtual CommodityPrice CommodityPrice { get; set; }
        public virtual ICollection<Order> CommissionOrders { get; set; }
        public virtual ICollection<Order> BuyOrders { get; set; }
        public virtual ICollection<Order> SellOrders { get; set; }
        public virtual ICollection<OrderLeg> SellOrderLegs { get; set; }
        public virtual ICollection<OrderLeg> BuyOrderLegs { get; set; }
        public virtual ICollection<OrderLeg> CommissionOrderLegs { get; set; }
        public virtual ICollection<AskLeg> AskLegs { get; set; }
        public virtual ICollection<AskLeg> AskLegs1 { get; set; }
        public virtual ICollection<Ask> Asks { get; set; }
        public virtual ICollection<Ask> Asks1 { get; set; }
    }
}
