//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.InfoExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLeg
    {
        public System.Guid OrderLegID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid BuyerUserID { get; set; }
        public int CommoditySellID { get; set; }
        public int CommodityBuyID { get; set; }
        public long SellQuantity { get; set; }
        public long BuyQuantity { get; set; }
        public int CommissionCommodityID { get; set; }
        public long Commission { get; set; }
        public long AskID { get; set; }
    
        public virtual Commodity SellCommodity { get; set; }
        public virtual Commodity BuyCommodity { get; set; }
        public virtual Commodity CommisionCommodity { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual Ask Ask { get; set; }
    }
}
