//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lind.InfoExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLegs = new HashSet<OrderLeg>();
        }
    
        public System.Guid OrderID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CommodityBuyID { get; set; }
        public int CommoditySellID { get; set; }
        public int CommissionCommodityID { get; set; }
        public long Commission { get; set; }
        public long AskID { get; set; }
    
        public virtual Commodity CommissionCommodity { get; set; }
        public virtual Commodity BuyCommodity { get; set; }
        public virtual Commodity SellCommdoity { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderLeg> OrderLegs { get; set; }
        public virtual Ask Ask { get; set; }
    }
}
